# obtained from http://www.id3.org/id3v2.3.0 2012.07.03
array set frameids {
  TALB    "Album/Movie/Show title"
  TBPM    "BPM (beats per minute)"
  TCOM    "Composer"
  TCON    "Content type"
  TCOP    "Copyright message"
  TDAT    "Date"
  TDLY    "Playlist delay"
  TENC    "Encoded by"
  TEXT    "Lyricist/Text writer"
  TFLT    "File type"
  TIME    "Time"
  TIT1    "Content group description"
  TIT2    "Title/songname/content description"
  TIT3    "Subtitle/Description refinement"
  TKEY    "Initial key"
  TLAN    "Language(s)"
  TLEN    "Length"
  TMED    "Media type"
  TOAL    "Original album/movie/show title"
  TOFN    "Original filename"
  TOLY    "Original lyricist(s)/text writer(s)"
  TOPE    "Original artist(s)/performer(s)"
  TORY    "Original release year"
  TOWN    "File owner/licensee"
  TPE1    "Lead performer(s)/Soloist(s)"
  TPE2    "Band/orchestra/accompaniment"
  TPE3    "Conductor/performer refinement"
  TPE4    "Interpreted, remixed, or otherwise modified by"
  TPOS    "Part of a set"
  TPUB    "Publisher"
  TRCK    "Track number/Position in set"
  TRDA    "Recording dates"
  TRSN    "Internet radio station name"
  TRSO    "Internet radio station owner"
  TSIZ    "Size"
  TSRC    "ISRC (international standard recording code)"
  TSSE    "Software/Hardware and settings used for encoding"
  TYER    "Year"
  TXXX    "User defined text information frame"
  TAL     "Album/Movie/Show title"
  TBP     "BPM (Beats Per Minute)"
  TCM     "Composer"
  TCO     "Content type"
  TCR     "Copyright message"
  TDA     "Date"
  TDY     "Playlist delay"
  TEN     "Encoded by"
  TFT     "File type"
  TIM     "Time"
  TKE     "Initial key"
  TLA     "Language(s)"
  TLE     "Length"
  TMT     "Media type"
  TOA     "Original artist(s)/performer(s)"
  TOF     "Original filename"
  TOL     "Original Lyricist(s)/text writer(s)"
  TOR     "Original release year"
  TOT     "Original album/Movie/Show title"
  TP1     "Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group"
  TP2     "Band/Orchestra/Accompaniment"
  TP3     "Conductor/Performer refinement"
  TP4     "Interpreted, remixed, or otherwise modified by"
  TPA     "Part of a set"
  TPB     "Publisher"
  TRC     "ISRC (International Standard Recording Code)"
  TRD     "Recording dates"
  TRK     "Track number/Position in set"
  TSI     "Size"
  TSS     "Software/hardware and settings used for encoding"
  TT1     "Content group description"
  TT2     "Title/Songname/Content description"
  TT3     "Subtitle/Description refinement"
  TXT     "Lyricist/text writer"
  TXX     "User defined text information frame"
  TYE     "Year"
}
