# obtained from http://www.id3.org/id3v2.3.0 2012.07.03
array set frameids {
  TALB    "Album/Movie/Show title"
  TBPM    "BPM (beats per minute)"
  TCOM    "Composer"
  TCON    "Content type"
  TCOP    "Copyright message"
  TDAT    "Date"
  TDLY    "Playlist delay"
  TENC    "Encoded by"
  TEXT    "Lyricist/Text writer"
  TFLT    "File type"
  TIME    "Time"
  TIT1    "Content group description"
  TIT2    "Title/songname/content description"
  TIT3    "Subtitle/Description refinement"
  TKEY    "Initial key"
  TLAN    "Language(s)"
  TLEN    "Length"
  TMED    "Media type"
  TOAL    "Original album/movie/show title"
  TOFN    "Original filename"
  TOLY    "Original lyricist(s)/text writer(s)"
  TOPE    "Original artist(s)/performer(s)"
  TORY    "Original release year"
  TOWN    "File owner/licensee"
  TPE1    "Lead performer(s)/Soloist(s)"
  TPE2    "Band/orchestra/accompaniment"
  TPE3    "Conductor/performer refinement"
  TPE4    "Interpreted, remixed, or otherwise modified by"
  TPOS    "Part of a set"
  TPUB    "Publisher"
  TRCK    "Track number/Position in set"
  TRDA    "Recording dates"
  TRSN    "Internet radio station name"
  TRSO    "Internet radio station owner"
  TSIZ    "Size"
  TSRC    "ISRC (international standard recording code)"
  TSSE    "Software/Hardware and settings used for encoding"
  TYER    "Year"
  TXXX    "User defined text information frame"
}
